## 1.Pre-Processing Data Before Import ( Convert Into Suitable Dataset )

### Movie DataSet

In [268]:
# removed_movie = []
# index = 0
# for movie in tqdm(np_movies):
#     if movie[0] not in np_genome[:,0]:
#         np_movies = np.delete(np_movies, index,0)
#         removed_movie.append(index)
#         continue
#     index += 1

100%|███████████████████████████████████████████████████████████████████████████| 62423/62423 [04:35<00:00, 226.97it/s]


In [350]:
# processed_movies = pd.DataFrame(np_movies, columns=movies.columns)
# processed_movies.to_csv('processed_movies.csv', encoding='utf-8', index=False)

### Mostly Genome ( Scores + Tags )

In [246]:
# def preprocess_tag():    
#     sort_tags = sorted(tag_count.items(), key=lambda x:x[1], reverse=True)[:550]
#     mostly_tags_df = pd.DataFrame(columns=genome_tags.columns)
#     tags_id = {}
#     for tag in sort_tags:
#         count = genome_tags.tag == tag[0]
#         if count.sum() != 1:
#             continue
#         else:
#             tag_index = genome_tags.tagId[count].values[0]
#             concat = pd.DataFrame([[tag_index, tag[0]]], columns=genome_tags.columns)
#             tags_id[tag[0]] = tag_index
#             mostly_tags_df = pd.concat([mostly_tags_df,concat], ignore_index=True)
#     return tags_id, mostly_tags_df

# tags_id, mostly_tags_df = preprocess_tag()

# genome = pd.merge(genome_scores,mostly_tags_df,on='tagId')

# np_genome = genome.to_numpy()

In [247]:
# genome.to_csv('processed_genome1.csv', encoding='utf-8', index=False)

### Tags Count

In [ ]:
# tag_count = {}
# for i in tqdm(range(len(np_genome_tags))):
#     count =  tags.tag[tags.tag == i].count()
# #     if count > 10:
#     tag_count[i] = int(count)

# import json
# with open("Tag_Count.json", "w") as write_file:
#     json.dump(tag_count, write_file, indent=4)

## 2. Import Libraries

In [2]:
import pandas as pd 
import numpy as np
from tqdm import tqdm
import json

## 3. Import DataSet and Convert into Array

In [5]:
# ratings = pd.read_csv("ratings.csv")
# movies = pd.read_csv("movies.csv")
# tags = pd.read_csv("tags.csv")
# genome_scores = pd.read_csv("genome-scores.csv")
# genome_tags = pd.read_csv("genome-tags.csv")
# genome = pd.merge(genome_scores,genome_tags,on='tagId')

In [265]:
ratings = pd.read_csv("ratings.csv")
movies = pd.read_csv("processed_movies.csv")
tags = pd.read_csv("tags.csv")
genome = pd.read_csv("processed_genome.csv")

In [3]:
# Opening JSON file
f = open('Tag_Count.json')
  
# returns JSON object as a dictionary
tag_count = json.load(f)

In [266]:
np_genome = genome.to_numpy()
np_movies = movies.to_numpy()
np_tags = tags.to_numpy()
np_ratings = ratings.to_numpy()
# np_genome_tags = genome_tags.to_numpy()

In [268]:
np_genome

array([[1, 19, 0.6625, 'action'],
       [2, 19, 0.64025, 'action'],
       [3, 19, 0.16025, 'action'],
       ...,
       [205383, 1096, 0.04175, 'war'],
       [205425, 1096, 0.0762499999999999, 'war'],
       [206499, 1096, 0.05025, 'war']], dtype=object)

## 4. Requirement Dict

### 4.1 Tags_Id

In [258]:
np.unique(genome.tagId)

array([5, 6, 7, 8, 9, 10, 12, 18, 19, 22, 23, 25, 28, 29, 42, 43, 44, 45,
       52, 57, 62, 63, 64, 65, 67, 70, 77, 79, 81, 86, 97, 100, 101, 107,
       108, 109, 110, 114, 120, 121, 122, 134, 138, 140, 141, 143, 145,
       155, 159, 164, 165, 168, 173, 177, 180, 183, 185, 192, 198, 201,
       202, 203, 204, 210, 211, 212, 215, 218, 220, 226, 227, 230, 232,
       235, 242, 246, 250, 251, 252, 253, 258, 262, 267, 268, 272, 274,
       275, 276, 278, 280, 282, 283, 284, 285, 286, 288, 289, 292, 296,
       297, 298, 300, 302, 303, 304, 305, 306, 308, 312, 313, 315, 316,
       317, 323, 325, 326, 331, 335, 336, 337, 339, 348, 349, 351, 354,
       359, 360, 361, 365, 368, 371, 374, 377, 378, 383, 385, 387, 388,
       393, 402, 406, 412, 414, 417, 419, 420, 423, 424, 425, 429, 430,
       435, 446, 448, 456, 460, 465, 467, 468, 471, 475, 484, 487, 490,
       494, 497, 498, 503, 505, 508, 509, 512, 518, 522, 524, 526, 528,
       529, 535, 536, 539, 540, 545, 547, 548, 549, 550, 551

In [259]:
np_genome

array([[1, 5, 0.14075, '1930s'],
       [2, 5, 0.091, '1930s'],
       [3, 5, 0.0474999999999999, '1930s'],
       ...,
       [205383, 1128, 0.03925, 'zombies'],
       [205425, 1128, 0.0285, 'zombies'],
       [206499, 1128, 0.0334999999999999, 'zombies']], dtype=object)

In [267]:
np.unique(np_genome[:,2])

array([0.001, 0.0012499999999999, 0.0015, ..., 0.999, 0.99925, 0.9995],
      dtype=object)

In [248]:
tags_id = {}
uniq_tag = np.unique(genome.tag)
uniq_tagID = np.unique(genome.tagId)
for index, tag in enumerate(uniq_tag):
    tags_id[tag] = (uniq_tagID[index],index)

### 4.2 Movies_Id

In [188]:
movies_id = {}
for index, movie in enumerate(np_movies):
    movies_id[movie[1]] = (movie[0], index)

In [125]:
item = 'Shrek the Third (2007)'
retrieved_item = 'Shrek (2001)'
tag = 'action'
direction = 0.5

## 5.2.1. Critique Distance

In [141]:
def rel_item(item,tag):
    movie_id = movies_id[item][0]
    tag_id = tags_id[tag][0]
    return float(np_genome[(np.where((np_genome[:,0] == movie_id) & (np_genome[:,1] == tag_id)))][:,2])

In [73]:
#rel_item_optimized 
def rel_all_items(tag):
    tag_index = tags_id[tag][1]
    len_movie = len(movies)
    rel_items = np_genome[tag_index*len_movie:tag_index*len_movie+len_movie,2].tolist()
    return rel_items

In [79]:
rel_all_items('zombies')[-1]

0.0334999999999999

In [81]:
def linear_sat(item,tag,direction):
    a = (rel_all_items(tag) - np.array(rel_item(item,tag)))*direction
    result = np.clip(a, 0, 1)
    return result

In [82]:
def diminish_sat(item,tag,direction):
    critique_dist = linear_sat(item,tag,direction)
    result = 1 - np.exp(-5*critique_dist)
    return result

In [15]:
rel_item(retrieved_item,tag)

0.4725

In [84]:
result = diminish_sat(item,tag,direction)
result

array([0.63850244, 0.61782437, 0.        , ..., 0.07109611, 0.01673341,
       0.44289414])

## 5.2.2. Item Similarity

In [249]:
def population():
    populations = {}
    for tag in tags_id:
        if tag not in tag_count.keys():
            tag_count[tag] = 0
        populations[tag] = tag_count[tag]
    return populations

In [250]:
populations = population()

In [251]:
def single_doc_freq(tag):
    # used to compute as the number of items where relevant greater tha 0.5 for only one tag 
    index = np.where(np_genome[:,3] == tag)
    count = (np_genome[index][:,2] > 0.5).sum()
    return count

In [252]:
single_doc_freq('action')

2139

In [253]:
def full_doc_freq():
    #used to comute doc_freq for all tags
    doc_freqs = {tag:0 for tag in tags_id}
    len_movies = len(movies)
    for i in tqdm(range(0,len(np_genome),len_movies)):
        tag = np_genome[i][-1]
        doc_freqs[tag] = (np_genome[i:i+len_movies,2] > 0.5).sum()
    return doc_freqs

In [254]:
doc_freqs = full_doc_freq()

100%|██████████████████████████████████████████████████████████████████████████████| 390/390 [00:00<00:00, 4295.33it/s]


In [255]:
def tags_weight(populations, doc_freqs, alpha = 0.000001):
    doc_freqs = np.array(list(doc_freqs.values()))
    populations = np.array(list(populations.values()))
    result = (np.array(populations) + alpha) / (doc_freqs + alpha)
    return np.clip(result,0,result.max())

In [256]:
weights = tags_weight(populations, doc_freqs)
len(weights)

390

In [134]:
def tag_item_vector(item):
    item_id = movies_id[item][0]
    full_tags_item = [np_genome[i][2] for i in np.where(np_genome[:,0] == item_id)[0]]  
#     if np.shape(full_tags_item) != (1128,):
#         full_tags_item = (np.zeros((1128,))+0.5).tolist()
    return full_tags_item

In [135]:
def cos_similarity(item, weights):
    
    # Create all movies's tags scores
    list_tags = np.zeros((len(movies),len(tags_id)))

    for index,tag_score in enumerate(np_genome[:,2]):
        tags_index = index // len(movies)
        movies_index = index - tags_index*len(movies)
        list_tags[movies_index,tags_index] = tag_score
        
    # Extract 1 query movie from matrix above 
    query_index = movies_id[item][1]
    query_tags = list_tags[query_index]
    
    numerator = np.dot(list_tags * list_tags[query_index],weights)
    
    denominator = np.sqrt(np.dot(list_tags**2, weights)) * np.sqrt(np.dot(query_tags**2, weights))
    
    result = numerator / denominator
    return result

In [257]:
cos_similarity('Shrek the Third (2007)',weights) #400 59 

array([0.67667893, 0.63645599, 0.75366591, ..., 0.51883937, 0.5565709 ,
       0.57872969])

In [22]:
def encode_movies():
    genres = {}
    index = 0
    movies_encode = []
    for movie in np_movies[:,2]:
        movie_encode = [0]*20
        for genre in movie.split('|'):
            if genre not in genres:
                genres[genre] = index
                index += 1
            movie_encode[genres[genre]] = 1
        movies_encode.append(movie_encode)
    return movies_encode

In [23]:
movies_encode = encode_movies()

In [24]:
def genres_similarity(item):
    index = movies_id[item][1]
    numerator = np.dot(movies_encode, movies_encode[index])
    denominator = np.sqrt(np.square(movies_encode[index]).sum()) * np.sqrt(np.sum(np.square(movies_encode),axis=1))
    return numerator/denominator

In [25]:
genres_similarity('Toy Story (1995)')

array([1.        , 0.77459667, 0.31622777, ..., 0.        , 0.4472136 ,
       0.4472136 ])

In [32]:
item = 'Shrek the Third (2007)'
retrieved_item = 'Shrek (2001)'
tag = 'classic'
direction = 0.5

In [29]:
list_critiques = [('action',0.5),('classic',0.5)]

In [30]:
def recommendation(item, list_critiques):
    a = 0
    for critique in list_critiques:
        tag = critique[0]
        direction = critique[1]
        value = diminish_sat(item,tag,direction)
        cos = cos_similarity(item, weights)
        genre_simi = genres_similarity(item)
        a += value * cos * genre_simi
    # progress_bar = tqdm(np_movies[:,1])

    score = {}

    for index, movie in enumerate(np_movies[:,1]):
        score[movie] = a[index]
    
    result = sorted(score.items(), key=lambda x:x[1], reverse=True)[:10]
    return result

In [33]:
recommendation(item, list_critiques)

[('Toy Story (1995)', 1.0720592385658756),
 ('Who Framed Roger Rabbit? (1988)', 0.9220524637695017),
 ('Shrek (2001)', 0.86742752708618),
 ('101 Dalmatians (1996)', 0.8407869352752536),
 ('Toy Story 2 (1999)', 0.8370900077143675),
 ('Nikitich and The Dragon (2006)', 0.7850536917938851),
 ('Incredibles, The (2004)', 0.7789901830941657),
 ('Finding Nemo (2003)', 0.7496725706136143),
 ('Space Jam (1996)', 0.744455033127308),
 ('Cat in the Hat, The (1971)', 0.7292440232628862)]

### Toi day thoi nha, Phan sau t de lai update dan` dan` a' 

In [417]:
movies_id["Twelve Tasks of Asterix, The (Les douze travaux d'Astérix) (1976)"]

(26340, 7423)

In [419]:
index = 3869
print('rel: ', rel_all_items(tag)[index])
print('linear ',linear_sat(item,tag,direction)[index])
print('dimi ',diminish_sat(item,tag,direction)[index])
print('cos ',cos[index])
print('genre ',genre_simi[index])

rel:  0.682
linear  0.30287500000000006
dimi  0.780054392096477
cos  0.7926676759967288
genre  0.9128709291752769


In [420]:
index = 7423
print('rel: ', rel_all_items(tag)[index])
print('linear ',linear_sat(item,tag,direction)[index])
print('dimi ',diminish_sat(item,tag,direction)[index])
print('cos ',cos[index])
print('genre ',genre_simi[index])

rel:  0.8585
linear  0.39112500000000006
dimi  0.8585239734602474
cos  0.7824276446434084
genre  0.9128709291752769


In [407]:
rel_item(item,tag)

0.0762499999999999

In [410]:
rel_item(retrieved_item,tag)

0.682

In [405]:
sorted(score.items(), key=lambda x:x[1], reverse=True)[:30]

[("Twelve Tasks of Asterix, The (Les douze travaux d'Astérix) (1976)",
  0.6132054278393179),
 ('Toy Story (1995)', 0.6097923156447862),
 ('Monsters, Inc. (2001)', 0.5690709330005551),
 ('Finding Nemo (2003)', 0.5690085042875217),
 ('Shrek (2001)', 0.5644499150724894),
 ('Land Before Time, The (1988)', 0.5258969507800617),
 ('Rabbit Seasoning (1952)', 0.5237035308080275),
 ('Mickey, Donald, Goofy: The Three Musketeers (2004)', 0.5221382682016416),
 ('Toy Story 2 (1999)', 0.5210363773449698),
 ('101 Dalmatians (One Hundred and One Dalmatians) (1961)',
  0.5204273336982295),
 ('Robin Hood (1973)', 0.5174882737419338),
 ('Looney, Looney, Looney Bugs Bunny Movie, The (1981)', 0.5050147137371742),
 ('Who Framed Roger Rabbit? (1988)', 0.4964904965181962),
 ('Bugs Bunny / Road Runner Movie, The (a.k.a. The Great American Chase) (1979)',
  0.49541329158142033),
 ('Aladdin (1992)', 0.4940054467812984),
 ('Rudolph, the Red-Nosed Reindeer (1964)', 0.4930313943730364),
 ('Asterix and Cleopatra (As

## 5.2.3. Algorithm for Responding to Critiques

In [59]:
def sorting(item,critiques):
    for tag, direction in critiques:
        
    #critiques = [tag,direction]
    

IndentationError: expected an indented block after function definition on line 1 (2447653407.py, line 1)

In [152]:
item

'Shrek the Third (2007)'

In [156]:
critiques = [('classic',0.5),('007',-0.5)]

In [154]:
footballers_goals = {'Eusebio': 120, 'Cruyff': 104, 'Pele': 150, 'Ronaldo': 132, 'Messi': 125}

sorted_footballers_by_goals = sorted(footballers_goals.items(), key=lambda x:x[1], reverse=True)
print(sorted_footballers_by_goals)

[('Pele', 150), ('Ronaldo', 132), ('Messi', 125), ('Eusebio', 120), ('Cruyff', 104)]


In [153]:
sorted_footballers_by_goals[2]

('Messi', 125)

In [151]:
list(footballers_goals.items())[:4]

[('Eusebio', 120), ('Cruyff', 104), ('Pele', 150), ('Ronaldo', 132)]

In [70]:
footballers_goals.items()

dict_items([('Eusebio', 120), ('Cruyff', 104), ('Pele', 150), ('Ronaldo', 132), ('Messi', 125)])

In [64]:
a[0][1]

0.5